### PR TITLE
Some small changes and SK translations

### PR DESCRIPTION
**Pull request by pylerSM**

### CODE REVIEW

**Comment by jackpf** [comment]
Awesome, I'll merge this when I get back home tomorrow

**Comment by pylerSM** [comment]
I think app needs new icon as soon as possible. Current one is ugly one :D

**Comment by jackpf** [comment]
@pylerSM Got a new string if you fancy translating it:
`<string name="error_no_connection">No connection</string>`

Also attempted to make a new icon, still not great though! if you can make a better one go for it :p

**Comment by pylerSM** [comment]
I will translate it. About new icon (https://github.com/jackpf/ApkDownloader/commit/7c1c7e804fc54311d0fdba652f4c70e6c02ee8aa), i think it is good now :)

**Pull request merged**
